/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server_client_stoppuhr;

/**
 *
 * @author user
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    public Client() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanCenter = new javax.swing.JPanel();
        jPanTime = new javax.swing.JPanel();
        jLabTime = new javax.swing.JLabel();
        jPanNorth = new javax.swing.JPanel();
        jlabRefreshrate = new javax.swing.JLabel();
        jSliTime = new javax.swing.JSlider();
        jlab1ms = new javax.swing.JLabel();
        jPanEast = new javax.swing.JPanel();
        jButConnection = new javax.swing.JButton();
        jButDisconnnect = new javax.swing.JButton();
        jButStart = new javax.swing.JButton();
        jButStop = new javax.swing.JButton();
        jButClear = new javax.swing.JButton();
        jButEnd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabTime.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabTime.setText("0.000");
        jLabTime.setPreferredSize(new java.awt.Dimension(50, 25));

        javax.swing.GroupLayout jPanTimeLayout = new javax.swing.GroupLayout(jPanTime);
        jPanTime.setLayout(jPanTimeLayout);
        jPanTimeLayout.setHorizontalGroup(
            jPanTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
            .addGroup(jPanTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanTimeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabTime, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanTimeLayout.setVerticalGroup(
            jPanTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
            .addGroup(jPanTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanTimeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabTime, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanCenter.add(jPanTime);

        getContentPane().add(jPanCenter, java.awt.BorderLayout.CENTER);

        jlabRefreshrate.setText("Refreshrate : 1s");
        jPanNorth.add(jlabRefreshrate);
        jPanNorth.add(jSliTime);

        jlab1ms.setText("1ms");
        jPanNorth.add(jlab1ms);

        getContentPane().add(jPanNorth, java.awt.BorderLayout.PAGE_START);

        jPanEast.setLayout(new java.awt.GridBagLayout());

        jButConnection.setText("Connect");
        jButConnection.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jButConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButConnectionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanEast.add(jButConnection, gridBagConstraints);

        jButDisconnnect.setText("Disconnect");
        jButDisconnnect.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jButDisconnnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDisconnnectActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanEast.add(jButDisconnnect, gridBagConstraints);

        jButStart.setText("Start");
        jButStart.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jButStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButStartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanEast.add(jButStart, gridBagConstraints);

        jButStop.setText("Stop");
        jButStop.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jButStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButStopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanEast.add(jButStop, gridBagConstraints);

        jButClear.setText("Clear");
        jButClear.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jButClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanEast.add(jButClear, gridBagConstraints);

        jButEnd.setText("End");
        jButEnd.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jButEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEndActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanEast.add(jButEnd, gridBagConstraints);

        getContentPane().add(jPanEast, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButConnectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButConnectionActionPerformed

    private void jButDisconnnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDisconnnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButDisconnnectActionPerformed

    private void jButStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButStartActionPerformed

    private void jButStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButStopActionPerformed

    private void jButClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButClearActionPerformed

    private void jButEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButEndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Client().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButClear;
    private javax.swing.JButton jButConnection;
    private javax.swing.JButton jButDisconnnect;
    private javax.swing.JButton jButEnd;
    private javax.swing.JButton jButStart;
    private javax.swing.JButton jButStop;
    private javax.swing.JLabel jLabTime;
    private javax.swing.JPanel jPanCenter;
    private javax.swing.JPanel jPanEast;
    private javax.swing.JPanel jPanNorth;
    private javax.swing.JPanel jPanTime;
    private javax.swing.JSlider jSliTime;
    private javax.swing.JLabel jlab1ms;
    private javax.swing.JLabel jlabRefreshrate;
    // End of variables declaration//GEN-END:variables
}
